### ISSUE TITLE
Extend pomo to notify for a Future time input in HH:MM 24 hrs format

### ISSUE THREAD

**Issue by sayan3296** [sayanarijit/pomo#3]
Right now pomo notifies the user based on the delay (in minutes) we pass as arg. So if the time is 09:00 now and I want myself to be notified at 11:00 AM, then 120 will be the value.

How about improving it to the extent so that, 

pomo -m 20 Take a break
   --> Will function as it is 

pomo -t 13:20 Take a break
   --> Will keep on checking until the system clock in 13:20 and then notify the user

Not sure if it makes sense but workaholic people like myself will probably find it helpful who often forget their lunch or dinner time while completely immersed in their laptop for some work. :)

**Comment by sayanarijit** [comment]
Hmm... It's the job of an alarm clock, not pomodoro timer :). The job of a pomodoro timer is to keep you healthy and also to help you focus on a single task by reminding you to take a break, review other tasks and do some movement like stretching, walking, jumping, dancing etc. every 'n' minutes (usually 25). Sitting continuously without movement is unhealthy or even deadly.

[source](https://en.m.wikipedia.org/wiki/Pomodoro_Technique)
